### PR TITLE
exlude unneeded files from crates.io

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
@hsivonen r?

**Comment by ignatenkobrain** [comment]
There are few reasons:

* No one needs that file when downloading tarball from crates.io (it's not even exposed anywhere)
* Including it makes tarball mentioned above larger

This doesn't remove this file from git repo or git archives, it is only about crates.io

**Comment by hsivonen** [comment]
> it's not even exposed anywhere

It's exposed via `cargo vendor`, which seems like the way one would expect an application distributor to comply with the GPL when shipping an app that depends on crates.io crates.

The file is 64 KB and it gets compressed as part of the tarball, so there doesn't seem to be a strong need to optimize it out and optimizing it out seems to make GPL compliance potentially even harder than it already is.

**Comment by hsivonen** [comment]
I'm going to make the file smaller on the `fastcjkencode` branch.

**Comment by hsivonen** [comment]
For reasons stated above, I'm not merging this and will instead make the file smaller and document why it's there.

**Comment by hsivonen** [comment]
Thanks for the pull request and sorry about not taking it.

**Comment by ignatenkobrain** [comment]
@hsivonen IANAL, but I think if you don't include file on crates.io tarball (but rather store in git), I believe you still comply with GPL.

I wanted it to be excluded because you can't make use of it from other crates, so packaging this file is pointless and creates additional work for me to exclude it in Fedora.

@spotrh, do you have any opinion on this?

**Comment by spotrh** [comment]
Standard disclaimer: IANAL, this is not legal advice.

I'm coming into this late, but "generate-encoding-data.py" doesn't seem to be GPL licensed (Apache 2.0 or MIT), so I'm not sure what its presence or placement has to do with GPL compliance.

**Comment by hsivonen** [comment]
@spotrh, I'm not a lawyer either and I recognize that you've thought about this stuff a lot more than I have. My thinking was this:

Person A creates a GPLed library. Person B distributes as binary an application that includes both person A's GPLed library and encoding_rs. I thought that in that case, GPL from person A's library requires person B to distribute the preferred form for making modifications to the whole application when distributing a binary. Arguably, for the sections of Rust code in encoding_rs that are the output of the Python script being excluded here, the preferred form for making modifications is the Python script and its input (a copy of the JSON files from the standard).

Thus, if the Python script is included on crates.io, when running `cargo vendor` it's easy-ish to drop a checkout of the standard (at the [indicated revision](https://github.com/whatwg/encoding/tree/f381389b0addceb96c16dd2602a84d82ab7a2390)!) next to the `encoding_rs` directory. If the Python script is excluded, it's harder piece the parts together.

(Apart from the distro's package managers within the scope of distros, I'm not aware of mechanisms other than `cargo vendor` than would make it even remotely practical to distribute the full corresponding source code of a `cargo`-built application binary, which is why I brought up `cargo vendor` above.)

**Pull request closed without merging**
