### PR TITLE
Add hack to allow building with stable rust

### PR DESCRIPTION
**Pull request by glandium**

### CODE REVIEW

**Comment by steveklabnik** [comment]
This has since broke Debian, causing ripgrep to be removed https://www.reddit.com/r/rust/comments/c8bgwf/ripgrep_dependency_has_been_marked_for/

I thought that the decision was to not ship this patch.

**Comment by hsivonen** [comment]
> This has since broke Debian,

More precisely, the breakage was the combined effect of this PR and [another PR in the `simd` crate](https://github.com/hsivonen/simd/pull/27). This crate stopped depending (the dependency used to be optional, but Debian exercised optional dependencies by (semi-?)automation, AFAICT) on the `simd` crate in February, so the combined effect was fixed here in upstream already in February.

Debian independently discovered the combined effect only in July, because Debian was still carrying a copy from January due to the Buster freeze but then made an exception to the freeze for `rustc` that triggered the problem. Still, as noted, the upstream correction was made already in February, so there's no corresponding July changeset here upstream.

The `simd` crate is obsolete and no longer builds regardless of its `build.rs`.

> causing ripgrep to be removed

`ripgrep` has not been removed, and it's not cool to make people believe that it has.

An automated system discovered a bug (again, already fixed here upstream in February) that _if left unaddressed_ could have lead to such removal. However, it was _not left unaddressed_ and was _quickly fixed_ in Debian. Such automated notifications and acting on them is, as I understand it, a rather mundane occurrence in Debian and should be considered an internal Debian matter.

> I thought that the decision was to not ship this patch.

The decision in February was not to replicate the hack form the `simd` crate in the `packed_simd` crate. As a result, despite not backing out this PR, `encoding_rs` hasn't compiled with the stable compiler if enabling the `simd-accel` feature since February. 

This, including the reason for not also backing out this PR, is explained (again, since February) by a comment in [`build.rs`](https://github.com/hsivonen/encoding_rs/blob/54cf6eb37d26237c3d62268f2cb7f57609e800eb/build.rs). You can verify this effect by trying to build `encoding_rs` with the `simd-accel` feature using the stable compiler. The build fails.

(Note that if you try to build `packed_simd` itself after selecting the stable compiler, the crate builds by automatically picking the nightly compiler you have installed, because it has a `rust-toolchain` override. To draw the right conclusions, you need to attempt building it as a dependency of another crate.)

**Comment by hsivonen** [comment]
> However, it was _not left unaddressed_ and was _quickly fixed_ in Debian.

Note that the fix went into Debian `unstable` but _deliberately_ didn't go into `testing`. Still, nothing was removed from `testing` either, because the user-facing experience wasn't broken, so `testing` wasn't changed to avoid a policy-motivated change causing an actual user-facing problem.

**Comment by sylvestre** [comment]
Correct, the only issue is going to be for Debian derivatives based on Debian stable (Ubuntu won't be impacted).
We (Debian developers) are going to fix that for a point release of Buster.

To me, this issue didn't deserve this escalation. This is pretty much business as usual in Linux distros.

**Pull request merged**
